package org.joe_e.servlet;

import javax.servlet.http.HttpSession;

/**
 * Abstract class whose subclass represent session instances for 
 * servlets. The SessionView is in fact the policy regarding what
 * subset of the session the servlet has access to. Members specified
 * in the SessionView will be visible from within the servlet's 
 * specification. Anything not explicitly declared in the SessionView
 * will be hidden from the servlet's methods. All JoeEServlets must
 * have an inner class called SessionView that extends this class. 
 * These inner classes can be auto-generated by an external tool.
 * @author akshay
 */
public abstract class AbstractSessionView {

	protected HttpSession session;

	/**
	 * default constructor
	 */
	public AbstractSessionView(HttpSession ses) {
		session = ses;
	}
}
